export const DISEASES = {
  heart: {
    label: 'Heart Disease',
    emoji: '🫀',
    color: 'heart',
    description: 'Predict coronary artery disease risk using the Cleveland dataset',
    fields: [
      { name: 'age',       label: 'Age',                type: 'number', min: 1,   max: 120, step: 1,   placeholder: '54',   unit: 'years',   hint: 'Patient age in years' },
      { name: 'sex',       label: 'Sex',                type: 'select', options: [{ value: 0, label: 'Female' }, { value: 1, label: 'Male' }] },
      { name: 'cp',        label: 'Chest Pain Type',    type: 'select', options: [
          { value: 0, label: 'Typical Angina' },
          { value: 1, label: 'Atypical Angina' },
          { value: 2, label: 'Non-Anginal Pain' },
          { value: 3, label: 'Asymptomatic' },
      ]},
      { name: 'trestbps',  label: 'Resting BP',         type: 'number', min: 60,  max: 250, step: 1,   placeholder: '130',  unit: 'mm Hg',   hint: 'Resting blood pressure' },
      { name: 'chol',      label: 'Cholesterol',        type: 'number', min: 100, max: 600, step: 1,   placeholder: '250',  unit: 'mg/dl',   hint: 'Serum cholesterol' },
      { name: 'fbs',       label: 'Fasting Blood Sugar',type: 'select', options: [{ value: 0, label: '≤120 mg/dl (Normal)' }, { value: 1, label: '>120 mg/dl (High)' }] },
      { name: 'restecg',   label: 'Resting ECG',        type: 'select', options: [
          { value: 0, label: 'Normal' },
          { value: 1, label: 'ST-T Abnormality' },
          { value: 2, label: 'LV Hypertrophy' },
      ]},
      { name: 'thalach',   label: 'Max Heart Rate',     type: 'number', min: 60,  max: 250, step: 1,   placeholder: '150',  unit: 'bpm',     hint: 'Maximum heart rate achieved' },
      { name: 'exang',     label: 'Exercise Angina',    type: 'select', options: [{ value: 0, label: 'No' }, { value: 1, label: 'Yes' }] },
      { name: 'oldpeak',   label: 'ST Depression',      type: 'number', min: 0,   max: 10,  step: 0.1, placeholder: '1.5',  unit: 'mm',      hint: 'ST depression induced by exercise' },
      { name: 'slope',     label: 'ST Slope',           type: 'select', options: [
          { value: 0, label: 'Upsloping' },
          { value: 1, label: 'Flat' },
          { value: 2, label: 'Downsloping' },
      ]},
      { name: 'ca',        label: 'Major Vessels',      type: 'number', min: 0,   max: 4,   step: 1,   placeholder: '0',    unit: 'vessels', hint: 'Colored by fluoroscopy (0–4)' },
      { name: 'thal',      label: 'Thalassemia',        type: 'select', options: [
          { value: 0, label: 'Normal' },
          { value: 1, label: 'Fixed Defect' },
          { value: 2, label: 'Reversible Defect' },
          { value: 3, label: 'Unknown' },
      ]},
    ],
  },

  diabetes: {
    label: 'Diabetes',
    emoji: '🩸',
    color: 'diabetes',
    description: 'Predict diabetes onset using the PIMA Indians dataset',
    fields: [
      { name: 'pregnancies',        label: 'Pregnancies',          type: 'number', min: 0, max: 20,  step: 1,   placeholder: '2',     unit: 'times',   hint: 'Number of pregnancies' },
      { name: 'glucose',            label: 'Glucose',              type: 'number', min: 0, max: 300, step: 1,   placeholder: '120',   unit: 'mg/dl',   hint: 'Plasma glucose concentration (2-hr OGTT)' },
      { name: 'blood_pressure',     label: 'Blood Pressure',       type: 'number', min: 0, max: 150, step: 1,   placeholder: '70',    unit: 'mm Hg',   hint: 'Diastolic blood pressure' },
      { name: 'skin_thickness',     label: 'Skin Thickness',       type: 'number', min: 0, max: 100, step: 1,   placeholder: '20',    unit: 'mm',      hint: 'Triceps skinfold thickness' },
      { name: 'insulin',            label: 'Insulin',              type: 'number', min: 0, max: 900, step: 1,   placeholder: '80',    unit: 'mu U/ml', hint: '2-Hour serum insulin' },
      { name: 'bmi',                label: 'BMI',                  type: 'number', min: 0, max: 70,  step: 0.1, placeholder: '28.5',  unit: 'kg/m²',   hint: 'Body mass index' },
      { name: 'diabetes_pedigree',  label: 'Diabetes Pedigree',    type: 'number', min: 0, max: 3,   step: 0.001, placeholder: '0.45', unit: '',       hint: 'Diabetes pedigree function (genetic risk)' },
      { name: 'age',                label: 'Age',                  type: 'number', min: 1, max: 120, step: 1,   placeholder: '33',    unit: 'years',   hint: 'Age in years' },
    ],
  },

  kidney: {
    label: 'Kidney Disease',
    emoji: '🫘',
    color: 'kidney',
    description: 'Predict chronic kidney disease using the UCI CKD dataset',
    fields: [
      { name: 'age',                 label: 'Age',                    type: 'number', min: 1,   max: 120,   step: 1,    placeholder: '50',    unit: 'years'   },
      { name: 'blood_pressure',      label: 'Blood Pressure',         type: 'number', min: 50,  max: 200,   step: 1,    placeholder: '80',    unit: 'mm Hg'   },
      { name: 'specific_gravity',    label: 'Specific Gravity',       type: 'number', min: 1.0, max: 1.03,  step: 0.005,placeholder: '1.015', unit: ''        },
      { name: 'albumin',             label: 'Albumin',                type: 'number', min: 0,   max: 5,     step: 1,    placeholder: '1',     unit: 'g/dl'    },
      { name: 'sugar',               label: 'Sugar',                  type: 'number', min: 0,   max: 5,     step: 1,    placeholder: '0',     unit: ''        },
      { name: 'red_blood_cells',     label: 'Red Blood Cells',        type: 'select', options: [{ value: 1, label: 'Normal' }, { value: 0, label: 'Abnormal' }] },
      { name: 'pus_cell',            label: 'Pus Cell',               type: 'select', options: [{ value: 1, label: 'Normal' }, { value: 0, label: 'Abnormal' }] },
      { name: 'pus_cell_clumps',     label: 'Pus Cell Clumps',        type: 'select', options: [{ value: 0, label: 'Not Present' }, { value: 1, label: 'Present' }] },
      { name: 'bacteria',            label: 'Bacteria',               type: 'select', options: [{ value: 0, label: 'Not Present' }, { value: 1, label: 'Present' }] },
      { name: 'blood_glucose_random',label: 'Blood Glucose (Random)', type: 'number', min: 50,  max: 500,   step: 1,    placeholder: '120',   unit: 'mg/dl'   },
      { name: 'blood_urea',          label: 'Blood Urea',             type: 'number', min: 5,   max: 400,   step: 1,    placeholder: '40',    unit: 'mg/dl'   },
      { name: 'serum_creatinine',    label: 'Serum Creatinine',       type: 'number', min: 0.1, max: 20,    step: 0.1,  placeholder: '1.2',   unit: 'mg/dl'   },
      { name: 'sodium',              label: 'Sodium',                 type: 'number', min: 100, max: 200,   step: 1,    placeholder: '140',   unit: 'mEq/L'   },
      { name: 'potassium',           label: 'Potassium',              type: 'number', min: 2,   max: 10,    step: 0.1,  placeholder: '4.5',   unit: 'mEq/L'   },
      { name: 'haemoglobin',         label: 'Haemoglobin',            type: 'number', min: 3,   max: 20,    step: 0.1,  placeholder: '14',    unit: 'g/dl'    },
      { name: 'packed_cell_volume',  label: 'Packed Cell Volume',     type: 'number', min: 10,  max: 60,    step: 1,    placeholder: '44',    unit: '%'       },
      { name: 'white_blood_cell_count', label: 'WBC Count',           type: 'number', min: 2000,max: 30000, step: 100,  placeholder: '8000',  unit: 'cells/μL'},
      { name: 'red_blood_cell_count',label: 'RBC Count',              type: 'number', min: 1,   max: 10,    step: 0.1,  placeholder: '5.0',   unit: 'million/μL'},
      { name: 'hypertension',        label: 'Hypertension',           type: 'select', options: [{ value: 0, label: 'No' }, { value: 1, label: 'Yes' }] },
      { name: 'diabetes_mellitus',   label: 'Diabetes Mellitus',      type: 'select', options: [{ value: 0, label: 'No' }, { value: 1, label: 'Yes' }] },
      { name: 'coronary_artery_disease', label: 'Coronary Artery Disease', type: 'select', options: [{ value: 0, label: 'No' }, { value: 1, label: 'Yes' }] },
      { name: 'appetite',            label: 'Appetite',               type: 'select', options: [{ value: 1, label: 'Good' }, { value: 0, label: 'Poor' }] },
      { name: 'pedal_edema',         label: 'Pedal Edema',            type: 'select', options: [{ value: 0, label: 'No' }, { value: 1, label: 'Yes' }] },
      { name: 'anemia',              label: 'Anemia',                 type: 'select', options: [{ value: 0, label: 'No' }, { value: 1, label: 'Yes' }] },
    ],
  },
}

export const MODEL_OPTIONS = [
  { value: 'best',                 label: '⭐ Auto (Best Model)' },
  { value: 'logistic_regression',  label: 'Logistic Regression' },
  { value: 'random_forest',        label: 'Random Forest' },
  { value: 'svm',                  label: 'Support Vector Machine' },
  { value: 'xgboost',              label: 'XGBoost' },
  { value: 'lightgbm',             label: 'LightGBM' },
  { value: 'stacking',             label: 'Stacking Ensemble' },
]
